In [2]:
import sys
print(sys.version)

3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]


array([[0.17797543, 0.96576739, 0.62780723, 0.04305759, 0.56716636,
        0.69213614, 0.17520922, 0.28752639],
       [0.17115056, 0.30202827, 0.41131507, 0.89174861, 0.80878043,
        0.29599695, 0.32608476, 0.43913895],
       [0.61839619, 0.98007865, 0.13348115, 0.7121517 , 0.42393917,
        0.81574113, 0.6146396 , 0.88549625],
       [0.01925007, 0.41273772, 0.74111239, 0.22767255, 0.13532915,
        0.4535145 , 0.82119504, 0.14570926],
       [0.70501812, 0.46925062, 0.65656253, 0.49683537, 0.94203173,
        0.05492132, 0.83204064, 0.17120449],
       [0.06677192, 0.59338079, 0.0446071 , 0.98403534, 0.72625683,
        0.61584149, 0.92134309, 0.75577109],
       [0.41030234, 0.39485137, 0.66341805, 0.60991435, 0.35664068,
        0.59544431, 0.25374636, 0.71039904],
       [0.92788662, 0.96246144, 0.78024297, 0.11386883, 0.02922009,
        0.67972307, 0.68269268, 0.41681076]])

In [11]:
def arrange(lis,cur):
    if cur+1==len(lis):
        print(lis)
    for i in range(cur,len(lis)):
        swap(lis,cur,i)
        arrange(lis,cur+1)
        swap(lis,cur,i)
def swap(lis,a,b):
    temp=lis[a]
    lis[a]=lis[b]
    lis[b]=temp
arrange(list(range(3)),0)

[0, 1, 2]
[0, 2, 1]
[1, 0, 2]
[1, 2, 0]
[2, 1, 0]
[2, 0, 1]


In [41]:
#a hello world of tensorflow
import tensorflow as tf
import time
tik=time.time()
hello=tf.constant(value="hello tensorflow")
sess=tf.Session()
print(sess.run(hello))
sess.close()
tok=time.time()
print("time is",(tok-tik)*1000,"ms")

b'hello tensorflow'
time is 32.0897102355957 ms


In [3]:
#tensorflow 和 numpy 的对比
import tensorflow as tf
import numpy as np
import time
#tensorflow version
tik=time.time()
#liner modle of tensorflow
w1=tf.Variable(tf.random_normal(shape=[2,3],stddev=1))
w2=tf.Variable(tf.random_normal(shape=[3,1],stddev=1))
x=tf.constant([[0.7,0.9]])
a=tf.matmul(x,w1)
y=tf.matmul(a,w2)
sess=tf.Session()
sess.run(w1.initializer)
sess.run(w2.initializer)
print("tensorflow version")
print("w1:",sess.run(w1))
print("w2:",sess.run(w2))
print("y",sess.run(y))
sess.close()
tok=time.time()
print("time is",(tok-tik)*1000,"ms")

#numpy version
tik=time.time()
x=np.asarray([[0.7,0.9]])
w1=np.random.random([2,3])
w2=np.random.random([3,1])
print("numpy version")
print("w1",w1)
print("w2",w2)
a=np.dot(x,w1)
y=np.dot(a,w2)
print("y",y)
tok=time.time()
print("time is",(tok-tik)*1000,"ms")
###注意tensorflow虽然是一个利用GPU的框架 但是因为数据传输等原因 在数据量不够多的时候性能表现并不如numpy

tensorflow version
w1: [[-0.8860047  -0.36807194 -0.43916655]
 [-0.07943188  0.14751324  0.01688445]]
w2: [[ 2.3421693 ]
 [-1.5836248 ]
 [-0.21659724]]
y [[-1.358989]]
time is 4962.038278579712 ms
numpy version
w1 [[0.24134989 0.49091698 0.73448587]
 [0.62041357 0.84691238 0.77988768]]
w2 [[0.6913827 ]
 [0.22295088]
 [0.50649472]]
y [[1.36532497]]
time is 2.0055770874023438 ms


In [48]:
#placeholder的用法
import tensorflow as tf
k=tf.constant(3.0)
b=tf.constant(5.0)
y=tf.placeholder(dtype="float32",shape=(1,100))
y=k*x+b
with tf.Session() as sess:
    pass    
#预定义没有出错

In [58]:
#placeholder的用法
import tensorflow as tf
import numpy as np
k=tf.constant(1.0)
b=tf.constant(1.0)
x=tf.placeholder(dtype="float32",shape=(1,100))
y=k*x+b
with tf.Session() as sess:
    print(sess.run(y,feed_dict={x:np.linspace(-1,1,100).reshape(1,100)}))
#这个地方是模拟了生成直线 feed机制接受numpy数组
#print(np.arange(10))

[[0.         0.02020204 0.04040402 0.06060606 0.0808081  0.10101008
  0.12121212 0.14141417 0.16161615 0.18181819 0.20202023 0.22222221
  0.24242425 0.2626263  0.28282827 0.3030303  0.32323235 0.34343433
  0.36363637 0.38383836 0.4040404  0.42424244 0.44444442 0.46464646
  0.4848485  0.50505054 0.5252525  0.5454545  0.56565654 0.5858586
  0.6060606  0.62626266 0.64646465 0.6666666  0.68686867 0.7070707
  0.72727275 0.7474748  0.7676768  0.78787875 0.8080808  0.82828283
  0.8484849  0.86868685 0.8888889  0.9090909  0.9292929  0.94949496
  0.969697   0.989899   1.010101   1.030303   1.050505   1.0707071
  1.0909091  1.1111112  1.1313131  1.1515151  1.1717172  1.1919192
  1.2121212  1.2323232  1.2525252  1.2727273  1.2929293  1.3131313
  1.3333334  1.3535354  1.3737373  1.3939394  1.4141414  1.4343435
  1.4545455  1.4747474  1.4949495  1.5151515  1.5353535  1.5555556
  1.5757575  1.5959597  1.6161616  1.6363636  1.6565657  1.6767676
  1.6969697  1.7171717  1.7373737  1.7575758  1.7777778 

In [34]:
# used tensorflow to let x to be limited
# in this way we do not use the whole neturl network 
# we only used the optimizer
import numpy as np
import tensorflow as tf

x = tf.Variable(8. ,dtype="float32")
y = x ** 3 - 2 * x ** 2 + x + 10
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    train = tf.train.GradientDescentOptimizer(0.003).minimize(y)
    print("init the y and the x")
    print("y=", sess.run(y))
    print("x=", sess.run(x))

    sess.run(train)
    print("after a train")
    print("y=", sess.run(y))
    print("x=", sess.run(x))

    for i in range(1000):
        sess.run(train)
    print("\nafter 1000s train\n")
    print("y=", sess.run(y))
    print("x=", sess.run(x))

    for i in range(1000):
        sess.run(train)
    print("\nafter 2000s train\n")
    print("y=", sess.run(y))
    print("x=", sess.run(x))

    print("it limited at the value x=%f y=%f" % (sess.run(x), sess.run(y)))

init the y and the x
y= 402.0
x= 8.0
after a train
y= 329.2567
x= 7.517

after 1000s train

y= 10.000003
x= 1.0014548

after 2000s train

y= 10.0
x= 1.0000099
it limited at the value x=1.000010 y=10.000000


In [3]:
# used tensorflow to test place holder
import numpy as np
import tensorflow as tf

x_value=np.array([5.,-6.,7.,-8.]).reshape(4,1)

x=tf.placeholder(dtype="float64",shape=(4,1))
w=tf.Variable(np.random.rand(3,4))
b=tf.Variable(np.random.rand(3,1))
y=tf.matmul(w,x)+b

init=tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print("\ninit time the values\n")
    print("x=",sess.run(x,feed_dict={x:x_value}))
    print("y=",sess.run(y,feed_dict={x:x_value}))
    print("b=",sess.run(b))
    train=tf.train.GradientDescentOptimizer(0.001).minimize(y)
    
    print("\nafter 1000 trains\n")
    for i in range(1000):
        sess.run(train,feed_dict={x:x_value})
    print("y=",sess.run(y,feed_dict={x:x_value}))
    print("b=",sess.run(b))
    
    print("\nafter 2000 trains\n")
    for i in range(1000):
        sess.run(train,feed_dict={x:x_value})
    print("y=",sess.run(y,feed_dict={x:x_value}))
    print("b=",sess.run(b))
        
    print("\nafter 10000 trains\n")
    for i in range(10000):
        sess.run(train,feed_dict={x:x_value})
    print("y=",sess.run(y,feed_dict={x:x_value}))
    print("b=",sess.run(b))
    
    print("\nafter 20000 trains\n")
    for i in range(10000):
        sess.run(train,feed_dict={x:x_value})
    print("y=",sess.run(y,feed_dict={x:x_value}))
    print("b=",sess.run(b))
    #根据此我们可以分析 算法没有收敛 cost function选择出错
    #此时如果用adam方法根本就不能用 请慎重选择


init time the values

x= [[ 5.]
 [-6.]
 [ 7.]
 [-8.]]
y= [[-1.59403259]
 [ 0.14099026]
 [ 0.95922634]]
b= [[0.22449214]
 [0.34498743]
 [0.00342151]]

after 1000 trains

y= [[-176.5940409 ]
 [-174.85901806]
 [-174.04078198]]
b= [[-0.77550791]
 [-0.65501262]
 [-0.99657854]]

after 2000 trains

y= [[-351.59404921]
 [-349.85902637]
 [-349.04079029]]
b= [[-1.77550796]
 [-1.65501266]
 [-1.99657859]]

after 10000 trains

y= [[-2101.59413233]
 [-2099.85910949]
 [-2099.04087341]]
b= [[-11.77550843]
 [-11.65501314]
 [-11.99657906]]

after 20000 trains

y= [[-3851.59421545]
 [-3849.85919261]
 [-3849.04095653]]
b= [[-21.77550891]
 [-21.65501361]
 [-21.99657954]]


In [2]:
# used tensorflow to let x to be limited
# in this way we do not use the whole neturl network 
# we only used the optimizer
import numpy as np
import tensorflow as tf

x = tf.Variable(8. ,dtype="float32")
y = x ** 3 - 2 * x ** 2 + x + 10
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    train = tf.train.GradientDescentOptimizer(0.003).minimize(y)
    print("init the y and the x")
    print("y=", sess.run(y))
    print("x=", sess.run(x))

    sess.run(train)
    print("after a train")
    print("y=", sess.run(y))
    print("x=", sess.run(x))

    for i in range(1000):
        sess.run(train)
    print("\nafter 1000s train\n")
    print("y=", sess.run(y))
    print("x=", sess.run(x))

    for i in range(1000):
        sess.run(train)
    print("\nafter 2000s train\n")
    print("y=", sess.run(y))
    print("x=", sess.run(x))

    print("it limited at the value x=%f y=%f" % (sess.run(x), sess.run(y)))

init the y and the x
y= 402.0
x= 8.0
after a train
y= 329.25662
x= 7.517

after 1000s train

y= 10.000002
x= 1.0014546

after 2000s train

y= 10.0
x= 1.0000099
it limited at the value x=1.000010 y=10.000000
